services:
  env-var-docs:
    image: python:3.13.2-slim@sha256:f2821f333099b62a286e6d0da85a89e29207a7b328d6c61660cf54334f5f2785
    container_name: civiform-vars-parser-package
    tty: true
    entrypoint: /bin/bash
    working_dir: /code
    volumes:
      - ../:/code
    environment:
      - PIP_ROOT_USER_ACTION=ignore
      - PIP_DISABLE_PIP_VERSION_CHECK=true
