name: Build

on:
  workflow_dispatch: {}

permissions: read-all

jobs:
  build_images:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    strategy:
      matrix:
        #id: [1, 2, 3, 4]
        id: [1]

    env:
      image: ghcr.io/gwendolyngoetz/app-${{ matrix.id }}
      tag: ghcr.io/gwendolyngoetz/app-${{ matrix.id }}:${{ github.run_id }}-${{ github.run_attempt }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          #username: ${{ secrets.DOCKER_USERNAME }}
          #password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Images ${{ env.tag }}
        run: docker buildx build --push --cache-from=type=gha --cache-to=type=gha,mode=max --file App.${{ matrix.id }}.Dockerfile --tag ${{ env.tag }} .

  run_images:
    needs: build_images

    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    strategy:
      matrix:
        id: [1]
        #id: [1, 2, 3, 4]
        label: [a, b, c]

    env:
      image: ghcr.io/gwendolyngoetz/app-${{ matrix.id }}
      tag: ghcr.io/gwendolyngoetz/app-${{ matrix.id }}:${{ github.run_id }}-${{ github.run_attempt }}

    steps:
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Images ${{ matrix.label }} ${{ env.tag }}
        run: docker run ${{ env.tag }}
