name: Build

on:
  workflow_dispatch: {}

permissions: read-all

jobs:
  build_images:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        id: [1, 2, 3, 4]

    env:
      tag: gwendolyngoetz/app-${{ matrix.id }}:${{ github.run_id }}-${{ github.run_attempt }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Images ${{ env.tag }}
        run: docker buildx build --push --file App.${{ matrix.id }}.Dockerfile --tag ${{ env.tag }} .

      - name: Run Images ${{ env.tag }}
        run: docker run ${{ env.tag }}

  #run_images:
  #  runs-on: ubuntu-latest

  #  steps:
  #    -name:
