name: Parent

on:
  push:
    branches: main
  workflow_dispatch: {}

permissions: read-all

jobs:
  run_parent:
    uses: ./.github/workflows/child.yaml
    secrets: inherit
    
  on_failure:
    needs: [ run_parent ]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: on_failure_step
        if: needs.run_parent.result == 'failure'
        run: echo "handle error"
