name: SBOM Generator

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: SBOM Generate
        uses: anchore/sbom-action@v0
        with:
          path: ./sampleproj/
      
      #- name: SBOM Publish with Release
      #  uses: anchore/sbom-action/publish-sbom@v0
      #  with:
      #    sbom-artifact-match: ".*\\.spdx$"
