# Generates the SBOM from our docker image and uploads the
# articact to the release
name: SBOM Generator Release

on:
  release:
    types: [ "created" ]

  workflow_dispatch: {}
  #  inputs:
  #    tag_name:
  #      description: 'The tag name of the release'
  #      required: true
        
permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    env:
      # Get the tag value from the workflow dispatch or the release event info
      TAG_NAME: ${{ github.event.inputs.tag_name || github.event.release.tag_name }}

    steps:
      - name: SBOM - Generate and Add to Release
        uses: anchore/sbom-action@v0
        with:
          #image: docker.io/civiform/civiform:${{ env.TAG_NAME }}
          #image: docker.io/civiform/mock-web-services:latest
          image: docker.io/civiform/civiform:v1.47.0
          github-token: ${{ secrets.GITHUB_TOKEN }}
