name: SBOM Generator Release

on:
  release:
    types: [ "created" ]

  workflow_dispatch:

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Print ${{ github.event.release.tag_name }}
        run: echo ${{ github.event.release.tag_name }}
        
#      - name: SBOM - Generate and Add to Release
#        uses: anchore/sbom-action@v0
#        with:
#          image: docker.io/civiform/mock-web-services:latest
#          github-token: ${{ secrets.GITHUB_TOKEN }}
