name: SBOM Generator Release

on:
  release:
    types: [ "created" ]

  workflow_dispatch:
    inputs:
      tag_name:
        description: 'The tag name of the release'
        required: true
        
permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    env:
      # Get the tag value from the workflow dispatch or the release event info
      TAG_NAME: ${{ github.event.inputs.tag_name || github.event.release.tag_name }}

    steps:
      - name: WD ${{ github.event.inputs.release_number }}
        run: echo ${{ github.event.inputs.release_number }}
        
      - name: EV ${{ github.event.release.tag_name }}
        run: echo ${{ github.event.release.tag_name }}

      - name: DYN ${{ env.TAG_NAME }}
        run: echo ${{ env.TAG_NAME }}
        

        
#      - name: SBOM - Generate and Add to Release
#        uses: anchore/sbom-action@v0
#        with:
#          image: docker.io/civiform/mock-web-services:latest
#          github-token: ${{ secrets.GITHUB_TOKEN }}
